admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: main-listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 6000 }
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcpj
          cluster: antifraud_cluster

  clusters:
  - name: antifraud_cluster
    connect_timeout: 2s
    type: logical_dns
    dns_lookup_family: V4_ONLY
    hosts:
    - socket_address:
        address: 0.0.0.0 #antifraud TODO
        port_value: 6001
    - socket_address:
        address: 0.0.0.0
        port_value: 6002
         
        
