apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: bff
  labels:
    app: bff
spec:
  selector:
    app: bff
  ports:
  - name: http
    port: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: felipemocruha/sistemas-distribuidos-bff:aula-1
        env:
        - name: KAFKA_HOSTS
          value: kafka-node.deps.svc.cluster.local:9092
        - name: REDIS_HOST
          value: redis.deps.svc.cluster.local
        - name: FAILURE_RATE
          value: "0.1"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 5001
