apiVersion: v1
kind: Service
metadata:
  name: kafka-node
  namespace: deps
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
  - name: tcp
    port: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-node
  namespace: deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        command: ["bash", "-c", "unset KAFKA_PORT; /etc/confluent/docker/run"]
        env:          
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-node.deps.svc.cluster.local:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: deps
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - name: tcp
    port: 2181
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        ports:
        - containerPort: 2181
