apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: deps
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: http
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4
        ports:
        - containerPort: 6379
