# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antifraud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='antifraud.proto',
  package='antifraud.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61ntifraud.proto\x12\x0c\x61ntifraud.v1\"w\n\x19\x41ntifraudAssesmentRequest\x12\x16\n\x0evalue_in_cents\x18\x01 \x01(\x03\x12\x1d\n\x15transaction_timestamp\x18\x02 \x01(\x03\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\"T\n\x1a\x41ntifraudAssesmentResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.antifraud.v1.AntifraudAssesmentStatus*6\n\x18\x41ntifraudAssesmentStatus\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\x32w\n\x0c\x41ntifraudAPI\x12g\n\x12\x41ntifraudAssesment\x12\'.antifraud.v1.AntifraudAssesmentRequest\x1a(.antifraud.v1.AntifraudAssesmentResponseb\x06proto3'
)

_ANTIFRAUDASSESMENTSTATUS = _descriptor.EnumDescriptor(
  name='AntifraudAssesmentStatus',
  full_name='antifraud.v1.AntifraudAssesmentStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=240,
  serialized_end=294,
)
_sym_db.RegisterEnumDescriptor(_ANTIFRAUDASSESMENTSTATUS)

AntifraudAssesmentStatus = enum_type_wrapper.EnumTypeWrapper(_ANTIFRAUDASSESMENTSTATUS)
ACCEPTED = 0
REJECTED = 1



_ANTIFRAUDASSESMENTREQUEST = _descriptor.Descriptor(
  name='AntifraudAssesmentRequest',
  full_name='antifraud.v1.AntifraudAssesmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value_in_cents', full_name='antifraud.v1.AntifraudAssesmentRequest.value_in_cents', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction_timestamp', full_name='antifraud.v1.AntifraudAssesmentRequest.transaction_timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='antifraud.v1.AntifraudAssesmentRequest.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='antifraud.v1.AntifraudAssesmentRequest.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=152,
)


_ANTIFRAUDASSESMENTRESPONSE = _descriptor.Descriptor(
  name='AntifraudAssesmentResponse',
  full_name='antifraud.v1.AntifraudAssesmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='antifraud.v1.AntifraudAssesmentResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=238,
)

_ANTIFRAUDASSESMENTRESPONSE.fields_by_name['status'].enum_type = _ANTIFRAUDASSESMENTSTATUS
DESCRIPTOR.message_types_by_name['AntifraudAssesmentRequest'] = _ANTIFRAUDASSESMENTREQUEST
DESCRIPTOR.message_types_by_name['AntifraudAssesmentResponse'] = _ANTIFRAUDASSESMENTRESPONSE
DESCRIPTOR.enum_types_by_name['AntifraudAssesmentStatus'] = _ANTIFRAUDASSESMENTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AntifraudAssesmentRequest = _reflection.GeneratedProtocolMessageType('AntifraudAssesmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANTIFRAUDASSESMENTREQUEST,
  '__module__' : 'antifraud_pb2'
  # @@protoc_insertion_point(class_scope:antifraud.v1.AntifraudAssesmentRequest)
  })
_sym_db.RegisterMessage(AntifraudAssesmentRequest)

AntifraudAssesmentResponse = _reflection.GeneratedProtocolMessageType('AntifraudAssesmentResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANTIFRAUDASSESMENTRESPONSE,
  '__module__' : 'antifraud_pb2'
  # @@protoc_insertion_point(class_scope:antifraud.v1.AntifraudAssesmentResponse)
  })
_sym_db.RegisterMessage(AntifraudAssesmentResponse)



_ANTIFRAUDAPI = _descriptor.ServiceDescriptor(
  name='AntifraudAPI',
  full_name='antifraud.v1.AntifraudAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=296,
  serialized_end=415,
  methods=[
  _descriptor.MethodDescriptor(
    name='AntifraudAssesment',
    full_name='antifraud.v1.AntifraudAPI.AntifraudAssesment',
    index=0,
    containing_service=None,
    input_type=_ANTIFRAUDASSESMENTREQUEST,
    output_type=_ANTIFRAUDASSESMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANTIFRAUDAPI)

DESCRIPTOR.services_by_name['AntifraudAPI'] = _ANTIFRAUDAPI

# @@protoc_insertion_point(module_scope)
